import "dart:io";
import "dart:collection";
import "dart:convert";
import "dart:async";

/// This class is the base for a socket that [XmppConnection] can use.
abstract class BaseSocketWrapper {
  /// This must return the unbuffered string stream that the socket receives.
  Stream<String> getDataStream();

  /// This must return errors generated by the socket.
  Stream<Object> getErrorStream();

  /// This must close the socket but not the streams so that the same class can be
  /// reused by calling [this.connect] again.
  void close();

  /// Write [data] into the socket.
  void write(String data);
  
  /// This must connect to [host]:[port] and initialize the streams accordingly.
  Future<void> connect(String host, int port);
}

/// TCP socket implementation for [XmppConnection]
class TCPSocketWrapper extends BaseSocketWrapper {
  late Socket _socket;
  final StreamController<String> _dataStream;
  final StreamController<Object> _errorStream;
  late StreamSubscription<dynamic> _socketSubscription;

  final void Function(String) _log;

  TCPSocketWrapper({ void Function(String) log = print })
  : _log = log,
  _dataStream = StreamController.broadcast(),
  _errorStream = StreamController.broadcast();

  Future<void> connect(String host, int port) async {
    this._socket = await SecureSocket.connect(host, port, supportedProtocols: [ "xmpp-client" ], timeout: Duration(seconds: 15));

    this._socketSubscription = this._socket.listen(
      (List<int> event) {
        this._dataStream.add(utf8.decode(event));
      },
      onError: (Object error) {
        this._log(error.toString());
        this._errorStream.add(error);
      }
    );
  }

  void close() {
    this._socket.close();
    this._socket.flush();
    this._socketSubscription.cancel();
  }

  Stream<String> getDataStream() => this._dataStream.stream.asBroadcastStream();
  Stream<Object> getErrorStream() => this._errorStream.stream.asBroadcastStream();
 
  void write(Object? object) {
    if (object != null && object is String) {
      this._log("==> " + object);
    }

    this._socket.write(object);
  }
}
